server:
  port: 80
  servlet:
    context-path: /
  tomcat:max-threads: 1000

spring:
  datasource:
    url: jdbc:mysql://47.110.52.14:3306/jtsys?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.cy: DEBUG


#page

#自定义每页显示多少项
db.page:
  pageSize: 3